import { CheckCircle2, CircleAlert, Info, Loader2, Plus, Search, X } from 'lucide-react';
import { useERP, formatMoney } from '../context/ERPContext';
export function Button({children,variant='primary',...p}){return <button className={`btn btn-${variant}`} {...p}>{children}</button>}
export function Card({children,className=''}){return <div className={`card ${className}`}>{children}</div>}
export function KPI({label,value,delta,icon:Icon,tone='blue'}){return <Card className="kpi"><div className={`kpi-icon ${tone}`}><Icon size={19}/></div><div className="kpi-body"><span>{label}</span><strong>{value}</strong>{delta&&<small className={delta.startsWith('-')?'negative':''}>{delta}</small>}</div></Card>}
export function Empty({text='لا توجد بيانات بعد'}){return <div className="empty"><Info size={30}/><strong>{text}</strong><span>ابدأ بإضافة أول سجل ليظهر هنا</span></div>}
export function SearchBar({value,onChange,placeholder='بحث في السجلات...'}){return <div className="searchbar"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange('')}><X size={15}/></button>}</div>}
export function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">TEYSSIR ERP</span><h3>{title}</h3></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
export function Toast(){const {toast}=useERP();if(!toast)return null;const Icon=toast.type==='success'?CheckCircle2:toast.type==='warning'?CircleAlert:Info;return <div className={`toast ${toast.type}`}><Icon size={19}/><span>{toast.message}</span></div>}
export function Table({columns,rows,onEdit,onDelete,empty='لا توجد بيانات'}){if(!rows.length)return <Empty text={empty}/>;return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}{(onEdit||onDelete)&&<th>إجراءات</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):row[c.key]}</td>)}{(onEdit||onDelete)&&<td><div className="row-actions">{onEdit&&<button className="text-btn" onClick={()=>onEdit(row)}>تعديل</button>}{onDelete&&<button className="text-btn danger" onClick={()=>onDelete(row)}>حذف</button>}</div></td>}</tr>)}</tbody></table></div>}
export function FormField({label,children,error}){return <label className="field"><span>{label}</span>{children}{error&&<small className="field-error">{error}</small>}</label>}
export { formatMoney, Plus };
